version: 2
sources:
  - name: analytics_339895848
    database: ubi-dng-hdb-live-prod
    tables:
      - name: events_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
      - name: events_intraday_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        

  - name: analytics_305405864
    database: dng-fhio-live-dev
    tables:
      - name: events_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
      - name: events_intraday_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
        
  - name: analytics_305256413
    database: dng-tcest-live
    tables:
      - name: events_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
      - name: events_intraday_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
        
  - name: analytics_336061606
    database: ubi-dng-hsah-live-prod
    tables:
      - name: events_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
      - name: events_intraday_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
        
  - name: analytics_305396465
    database: dng-imt-live
    tables:
      - name: events_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        
      - name: events_intraday_*
        loaded_at_field: event_timestamp
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 48
            period: hour
        